### ISSUE TITLE
/locations too strict in checking station coordinates

### ISSUE THREAD

**Issue by Teddy-1000** [EURODEO/e-soh#105]
Stations can move or have their position updated to be more precise. As in the example below. I think we should disable this check for now, and find a better way to make sure the position does not diverge too much between time series. In this case the position have moved 1.2 meters, but breaks the entire /locations endpoint of the API. I think such a check should be made somewhere else. As we do not want data with errors accepted in to the system at all, and we should treat the datastore as a source of truth.
```
{
    "detail": {
        "coordinates": "Station with id `0-578-0-91695 has multiple coordinates: {(20.914, 69.9367), (20.914, 69.93667)}"
    }
}
```

**Comment by lukas-phaf** [comment]
I assume the check you are referring to is the one where we check that `platform_coordinates` has only one entry per station.
If we remove it, and there are multiple ones, which one would you use? We have to make sure we don't ping-pong between multiple values on different requests. 

In some sense I think this check failing is a good indication that the ingested data is "wrong".

**Comment by Teddy-1000** [comment]
I know @jo-asplin-met-no  is currently working on a new gRPC method for use in `/locations` and I think we should solve this in the same function.
How important is it that the coordinates in `/location` match with the data? If this is not very important I suggest that the new method get the latest position provided for that station. It is not perfect, but is in line with how we treat other parameters where the latest provided is considered the most correct.

**Comment by Teddy-1000** [comment]
But I think having two divergent time series bringing down the entire `/locations` endpoint is bad.

**Comment by Teddy-1000** [comment]
Ok, temporary solution. We check that the diverging points are not too far apart, if within tolerance we sort the coordinates and choose the first one?

**Comment by lukas-phaf** [comment]
There is no concept of station in the store, only timeseries. The current `/locations` endpoint gets the latest location for each timeseries, so the blowup is not due directly to a timeseries position change, but due to different timeseries (actually the last observation of that timeseries) "belonging" to the same station reporting a different position. The underlying problem behind this might still be a station move, however.

But taking the last position in itself doesn't solve this problem, as there could be different positions with the same timestamp, from different timeseries/parameters.

Anyway, I agree with proceeding if the positions are close enough. Any approach that gives a consistent output is fine with me, although it feels strange to use the "smallest" coordinate.

**Comment by Teddy-1000** [comment]
I opened a PR with a draft for getting coordinates in a consistent manner.

**Comment by jo-asplin-met-no** [comment]
I updated Issue #107 with quite a lot of details to sketch a possible solution where the data store takes responsibility. @Teddy-1000 @lukas-phaf please comment!
